apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: searchservice
  template:
    metadata:
      labels:
        app: searchservice
    spec:
      containers:
        - name: searchservice
          image: ninoverhaegh/searchservice:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
